### PR TITLE
Fix test_dbm_gnu & allocation alignment (FTBFS on ppc64le and x86-64)

### PR DESCRIPTION
**Pull request by encukou**
This inserts patch 00311, taken from https://bugs.python.org/issue33901
Upstream lists the fix as being for macOS, but apparently it's ppc64le-specific (and probably specific to gdbm 1.15+).

Github shows all commits on top of 00311 in the diff; a direct comparison is here: https://github.com/fedora-python/cpython/compare/fedora-3.5..encukou:fedora-3.5

### CODE REVIEW

**Comment by hroncok** [comment]
Nice finding!

**Comment by vstinner** [comment]
> This inserts patch 00311, taken from https://bugs.python.org/issue33901

LGTM. It only impacts a test, and the backport looks straightforward.

**Comment by vstinner** [comment]
Did you try a scratch build on your PR to see if it repairs the build on ppc64le?

**Comment by encukou** [comment]
Yes, https://koji.fedoraproject.org/koji/taskinfo?taskID=62160426

Meanwhile, I'm still looking at the x86 failure. I think it'd be good to merge them together.

**Comment by vstinner** [comment]
> Yes, https://koji.fedoraproject.org/koji/taskinfo?taskID=62160426

Oh, it succeeded, great!

**Comment by encukou** [comment]
Thanks to Victor who [remembered the commit to backport](https://bugzilla.redhat.com/show_bug.cgi?id=1923658#c14), the x86-64 should be fixed as well. New scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=62283780

**Comment by encukou** [comment]
But, please review the Fedora PR instead: https://src.fedoraproject.org/rpms/python3.5/pull-request/17

**Pull request closed without merging**
