### PR TITLE
3.8.0a3 Fedora patches

### PR DESCRIPTION
**Pull request by hroncok**
Those are all of our patches as of 3.8.0a3 in Fedora rawhide (31).

This was HEAD: https://src.fedoraproject.org/rpms/python38/c/084a366e3d465801793c881800b016a776ba7c68

I've applied the patches, using dates where they were introduced (except some of the initial patches, where I've used the date of python3 package initial import), I've also tried to attribute all authors (except some of the initial patches, where I didn't bother to digg deeper than to attribute David Malcolm).

@vstinner and @stratakis Please review if the patches reflect the reality. If you find something wrong in our patches, note it down, we should address that later. 

On Monday, a4 should be released, I'll just take this and rebase it on that tag.

Thanks

### CODE REVIEW

**Comment by hroncok** [comment]
Notes from me: I think we should merge 102 and 205 to one patch, or upstream 205 before we upstream 102.

**Comment by hroncok** [comment]
Note that GitHub sorts the patches by date.  In git history, they are sorted by their number.

**Comment by stratakis** [comment]
I believe we can drop patch0001 according to https://bugs.python.org/issue36659 and https://pagure.io/packaging-committee/issue/886

**Comment by hroncok** [comment]
> I believe we can drop patch0001 according to https://bugs.python.org/issue36659 and https://pagure.io/packaging-committee/issue/886

Not until FPC 886 happens.

Also, let me make this absolutely important:

:warning: :warning: :warning: **Please review that this reflects the reality.** :warning: :warning: :warning: 

(Changes suggestions are good, but please don't let them steal this PR, they won't be addressed here.)

**Comment by vstinner** [comment]
I'm unhappy with the branch name: "3.8.0a3-f31-1". It sounds like it will be hard for me to update frequently my local checkout of the branch if it should at each Python release. I suggest to use the branch name "fed-3.8". If we care of keeping history of this branch on a rebase, we can now create a tag *before* a rebase:

```
git checkout fed-3.8
git branch fed-3.8-3.8.0a3
git push --tags
git rebase 3.8
git push origin HEAD -f  # push rewritten fed-3.8 branch
```

Would it be possible to simply drop the Fedora version from the branch name? I propose to have a fork to simply your job. But having N branch of the same Python version sounds like more work to me.

Let me see the package "python3" : https://src.fedoraproject.org/rpms/python3/ If I compare f30 and master branches: f30 is only "outdated" compared to master: f30 branch is at 3.7.3-1, whereas master branch is at 3.7.3-2. The pull request https://src.fedoraproject.org/rpms/python38/pull-request/13 basically "rebase" f30 on master. After this PR, the content of the 2 branches will be basically the same.

The comparison of f29 and f30 is more interesting. f30 specfile has an additional redhat-rpm-config BuildRequires. CFLAGS, LDFLAGS, etc. are different. Apart of that, patches look basically the same: it's just that 00274-fix-arch-names.patch has been updated in f30.

The comparison of f28 and f29 is hard to because because "python3" in f28 means Python 3.6 and "python3" in f29 means Python 3.7.

The more general question is if it makes sense to modify a patch of an old version of Fedora (ex: f29) but not on more recent version (ex: f30 and f31). For me, we should only "go forward": Fedora N should always be based on Fedora N+1. At some point, we can decide to stop updating Fedora N (ex: EOL). I'm talking about the same Python version: python36 package of f28 and python3 packaging of f29 should use the same Git source branch (ex: fed-3.6).

> I believe we can drop patch0001 according to https://bugs.python.org/issue36659 and https://pagure.io/packaging-committee/issue/886

I don't think that we should should take this PR as an opportunity to rework all downstream patches. I suggest to propose with a 1-to-1 mapping with what we already have. Creating this work is already hard enough.

**Comment by hroncok** [comment]
> I'm unhappy with the branch name: "3.8.0a3-f31-1". It sounds like it will be hard for me to update frequently my local checkout of the branch if it should at each Python release. I suggest to use the branch name "fed-3.8". If we care of keeping history of this branch on a rebase, we can now create a tag before a rebase...

Sure. Let's make it `fedora-3.8` - I have no issue with that.

> Would it be possible to simply drop the Fedora version from the branch name?

Nope, if we want to use this repo for all fedora versions. We have different patches in different versions  - when we do breaking changes, we do them in rawhide only.

We can have a branch without Fedora version to mean rawhide (and everything that happens to be the same).

> I propose to have a fork to simply your job.

What fork? I have a fork. This is also a fork. Please, be more specific.

> But having N branch of the same Python version sounds like more work to me.

More work than what? Than maintaining my own branches in my own fork? That's the exact same amount of work + confusion.

> Let me see the package "python3" : https://src.fedoraproject.org/rpms/python3/ If I compare f30 and master branches: f30 is only "outdated" compared to master: f30 branch is at 3.7.3-1, whereas master branch is at 3.7.3-2. The pull request https://src.fedoraproject.org/rpms/python38/pull-request/13 basically "rebase" f30 on master. After this PR, the content of the 2 branches will be basically the same.

Yes, that is correct. Until breaking changes are made, we try to keep it that way.

> The comparison of f29 and f30 is more interesting. f30 specfile has an additional redhat-rpm-config BuildRequires. CFLAGS, LDFLAGS, etc. are different. Apart of that, patches look basically the same: it's just that 00274-fix-arch-names.patch has been updated in f30.

Yes, that's correct, the breaking changes between f29 and f30 didn't involve any patches.
The patch difference is only there because nobody bothered to backport it (and it was not needed).
The arch-names patch changed for the sake of RHEL similarity, the change has no effect in Fedora.

> The more general question is if it makes sense to modify a patch of an old version of Fedora (ex: f29) but not on more recent version (ex: f30 and f31).

It might. When the older Fedora version has the python3 package on older Python version (aka today F28 has python3 as 3.6 but F29+ has it on 3.7), and you need to patch python3 but the change is not important on python3X package (python36 in Fedora 29+ in the given example). In that case, you only patch older Fedoras. But sure, the patches *can* be added to python3X in newer Fedoras as well, except that that is actually *more* work.

> For me, we should only "go forward": Fedora N should always be based on Fedora N+1.

I would agree, with the exception of the situation described in the previous step.

> At some point, we can decide to stop updating Fedora N (ex: EOL).

We do that, yes.

> I'm talking about the same Python version: python36 package of f28 and python3 packaging of f29 should use the same Git source branch (ex: fed-3.6).

And that's the problem.

> I don't think that we should should take this PR as an opportunity to rework all downstream patches. I suggest to propose with a 1-to-1 mapping with what we already have. Creating this work is already hard enough.

:+1:  :100:

Also, note that I'd rather figure the proper workflow (branch names, backport strategies, whatnot...) ad hoc. We don't need to write it down and define it here.  We can start with `fedora-3.8` and see where that brings us, only diverge `fedora-3.8-f30` for example when we change stuff in Fedora 31 beyond recognition but don't have to do it before then. This is totally not important at this point. Since we will rebase, it's not like we are creating unchangeable rules here. Consider the branch name here arbitrary so we can have a PR that has the patches.

Note that I seriously need somebody to review if this reflects the reality **now** so I can use it on a4 on Monday. We can bikeshed about branch names for weeks if you want to.

**Comment by torsava** [comment]
> The more general question is if it makes sense to modify a patch of an old version of Fedora (ex: f29) but not on more recent version (ex: f30 and f31).

I think this question is not relevant, because we definitely want to have the ability to do the reverse - patch new version, but not the old version. E.g. Fedora 30 and 31 might have the same Python version, but in F31 there's a breaking change to gcc that needs to be patched, but can't be patched in F30.

**Comment by torsava** [comment]
@hroncok 

Commit message for `00102` is missing `Only used when "%%{_lib}" == "lib64"` from the patch comment. I'd rather include it to avoid ambiguity.

**Comment by torsava** [comment]
Commit for `00111` is missing `Downstream only: not appropriate for upstream` from the comment. I think we should have all downstream-only patches clearly labelled so.

**Comment by torsava** [comment]
Interestingly, commit 102 is applied only conditionally:

    %if "%{_lib}" == "lib64"
    %patch102 -p1
    %endif

How does that map to this git approach to patches?

We could make a 64bit branch with this additional commit that is rebased upon the main branch. But that feels slightly too convoluted. But leaving it as a patch is not ideal either.

**Comment by torsava** [comment]
Patch 189 also applied conditionally. With a different condition, complicating matters further.

    %if %{with rpmwheels}
    %patch189 -p1
    rm Lib/ensurepip/_bundled/*.whl
    %endif

We can't get rid of that condition, as it's necessary for bootstrapping. Thus I think we'll have to leave conditional patches as standard dist-git patches.

**Comment by torsava** [comment]
I've checked all the commit messages and the commits/patches themselves, and everything looks good besides comments above.

**Comment by hroncok** [comment]
As for conditionally applied patches: We don't need new branches for those as long as the next patches needn't to be changed based on whether those were applied - and that would be a giant problem anyway even without git.

We'll use git to manage the patches and to help us rebase them, but we will still continue to apply them from files.

I'll amend the commit messages. Thanks!

**Comment by torsava** [comment]
> We'll use git to manage the patches and to help use rebase them, but we will still continue to apply them from files.

Oh I see! I thought we would just have the already patched sources as sources for the specfile. I guess this was covered on the demo I haven't seen, sorry!

**Comment by hroncok** [comment]
Thanks @torsava.

Pushed this to `fedora-3.8` volatile (as in: we will push force there) branch, tagged as stable (as in: will remain unchanged forever) tag `fedora-3.8.0a3`.

**Pull request merged**
