### PR TITLE
00440: gh-124160: Pass main_tstate to update_global_state_for_extensi…

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by hroncok** [comment]
Hey @luk1337. Do you need this in the Fedora package? What is the context?

**Comment by luk1337** [comment]
> Hey @luk1337. Do you need this in the Fedora package? What is the context?

Yes, this fixes a pretty critical bug IMO that affects the package I maintain.

* https://github.com/python/cpython/issues/124160
* https://github.com/weechat/weechat/issues/2190

**Comment by hroncok** [comment]
I see. I can get it in. Thanks for the PR.

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python3.13/pull-request/112
https://src.fedoraproject.org/rpms/python3.13/pull-request/113

**Comment by hroncok** [comment]
I rebased this slightly but I cannot push it into your branch. Could you please allow that in the PR options? It's not a big deal, except this won't be marked as merged if I don't do that.

**Comment by luk1337** [comment]
> I rebased this slightly but I cannot push it into your branch. Could you please allow that in the PR options? It's not a big deal, except this won't be marked as merged if I don't do that.

It was already enabled
image

**Comment by luk1337** [comment]
> > I rebased this slightly but I cannot push it into your branch. Could you please allow that in the PR options? It's not a big deal, except this won't be marked as merged if I don't do that.
> 
> It was already enabled image

I just clicked it twice tho, maybe that'll help somehow

**Comment by hroncok** [comment]
```
ERROR: Permission to luk1337/cpython.git denied to hroncok.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

:/

Nevermind. It's not important.

**Comment by luk1337** [comment]
yeah, I'm fine with you just pushing to origin instead.

**Comment by hroncok** [comment]
F41: https://bodhi.fedoraproject.org/updates/FEDORA-2024-5e3a30eef5
F42: https://bodhi.fedoraproject.org/updates/FEDORA-2024-e872ae1f6d

**Pull request closed without merging**
