### PR TITLE
Fix C99 build error: declare explicitly functions

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
Extract of Fedora 40 Koschei build: https://kojipkgs.fedoraproject.org/work/tasks/1249/107041249/build.log

```
/builddir/build/BUILD/Python-2.7.18/Objects/object.c: In function ‘_PyObject_DebugTypeStats’:
/builddir/build/BUILD/Python-2.7.18/Objects/object.c:2374:5: error: implicit declaration of function ‘_PySet_DebugMallocStats’; did you mean ‘_PyInt_DebugMallocStats’? [-Werror=implicit-function-declaration]
 2374 |     _PySet_DebugMallocStats(out);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
      |     _PyInt_DebugMallocStats
/builddir/build/BUILD/Python-2.7.18/Objects/object.c:2375:5: error: implicit declaration of function ‘_PyTuple_DebugMallocStats’; did you mean ‘_PyFrame_DebugMallocStats’? [-Werror=implicit-function-declaration]
 2375 |     _PyTuple_DebugMallocStats(out);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |     _PyFrame_DebugMallocStats
cc1: some warnings being treated as errors
make: *** [Makefile:1380: Objects/object.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by vstinner** [comment]
cc @stratakis @hroncok

I added patch id 405 to https://fedoraproject.org/wiki/SIGs/Python/PythonPatches

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python2.7/pull-request/55

**Comment by vstinner** [comment]
Thanks for the review @hroncok.

**Pull request merged**
