### PR TITLE
00378-support-expat-2.4.5.patch

### PR DESCRIPTION
**Pull request by stratakis**
00378 #
Make test suite support Expat >=2.4.5

Upstream: https://bugs.python.org/issue46811

### CODE REVIEW

**Comment by stratakis** [comment]
Scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=83531293

**Comment by hroncok** [comment]
Looks OK. Could you open a PR at https://src.fedoraproject.org/rpms/python3.11/pull-requests ? It's easier for me to verify.

**Comment by hroncok** [comment]
Also, note that 3.11.0a6 is to be released soon (planned for yesterday), so the backport here is probably not needed unless we really need to rebuild it now.

**Comment by stratakis** [comment]
Closing this, better to wait for the update.

**Pull request closed without merging**
