### PR TITLE
00378-support-expat-2.4.5.patch

### PR DESCRIPTION
**Pull request by stratakis**
00378 #
Fix the test suite support for Expat >= 2.4.5

Upstream: https://bugs.python.org/issue46811

### CODE REVIEW

**Comment by stratakis** [comment]
Downstream PR: https://src.fedoraproject.org/rpms/python2.7/pull-request/29

**Comment by hroncok** [comment]
The original commit message contains relevant references and authorship information. Could you please not strip that all down? It looks like you took an extra step by restricting the commit message to the bare minimum.

**Comment by stratakis** [comment]
> The original commit message contains relevant references and authorship information. Could you please not strip that all down? It looks like you took an extra step by restricting the commit message to the bare minimum.

Yes that is correct. Would you prefer the whole original commit message there? If not please post here the exact commit message you would prefer.

**Comment by hroncok** [comment]
I'd keep it all. That would have been the default easiest option :yum:

**Comment by stratakis** [comment]
Pushed directly to the repo.

**Pull request closed without merging**
