### PR TITLE
00338: test_stack_overflow from test_faulthandler hangs when python h…

### PR DESCRIPTION
**Pull request by stratakis**
…as been compiled with gcc 10.

Fixed upstream: https://bugs.python.org/issue38965

### CODE REVIEW

**Comment by hroncok** [comment]
I would rather just cherry-pick https://github.com/python/cpython/commit/f4a21d3b239bf4f4e4e2a8a5936b9b040645b246 and only amend the commit message to include the number. Why rewriting it?

**Comment by hroncok** [comment]
Thanks. 3.8.1rc1 should contain the fix. Let's just update instead?

**Comment by stratakis** [comment]
We can do that, but bear in mind that this will most possibly required for the alternative interpreters as well, python37, python36 etc. And I'd rather have that in the distro as soon as possible to not block the gcc folks.

**Comment by hroncok** [comment]
I am updating the 3.8 stack. The alternate versions do not block the gcc folks, do they?

**Comment by vstinner** [comment]
> Thanks. 3.8.1rc1 should contain the fix. Let's just update instead?

Right. So this PR became outdated, no?

**Comment by hroncok** [comment]
Yes.

**Comment by stratakis** [comment]
> I am updating the 3.8 stack. The alternate versions do not block the gcc folks, do they?

They do, they are being rebuilt as well.

**Comment by stratakis** [comment]
> > I am updating the 3.8 stack. The alternate versions do not block the gcc folks, do they?
> 
> They do, they are being rebuilt as well.

They are not blocking the entire distro, but still fail

**Comment by hroncok** [comment]
We should fix those, yes.

**Pull request closed without merging**
